"""Creación inicial de tablas

Revision ID: b7b3082a45dc
Revises: 
Create Date: 2025-10-16 09:21:53.655544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7b3082a45dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prestador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=150), nullable=False),
    sa.Column('cuit', sa.String(length=13), nullable=True),
    sa.Column('titular_nombre', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('contacto_responsable', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('descripcion_visita', sa.Text(), nullable=True),
    sa.Column('tiene_material_digital', sa.Boolean(), nullable=True),
    sa.Column('meses_disponibles', sa.String(length=200), nullable=True),
    sa.Column('dias_disponibles', sa.String(length=100), nullable=True),
    sa.Column('horarios_sugeridos', sa.String(length=50), nullable=True),
    sa.Column('detalle_horarios', sa.Text(), nullable=True),
    sa.Column('duracion_visita', sa.String(length=50), nullable=True),
    sa.Column('visitantes_maximo', sa.Integer(), nullable=True),
    sa.Column('recorridos_por_turno', sa.Integer(), nullable=True),
    sa.Column('edades_recomendadas', sa.String(length=200), nullable=True),
    sa.Column('acceso_movilidad_reducida', sa.String(length=20), nullable=True),
    sa.Column('afectado_por_lluvia', sa.String(length=50), nullable=True),
    sa.Column('tiene_personal', sa.Boolean(), nullable=True),
    sa.Column('tipo_reserva', sa.String(length=50), nullable=True),
    sa.Column('costo_referencia', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuit')
    )
    op.create_table('solicitud_visita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_institucion', sa.String(length=150), nullable=False),
    sa.Column('tipo_institucion', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('localidad', sa.String(length=100), nullable=True),
    sa.Column('responsable_nombre', sa.String(length=100), nullable=False),
    sa.Column('responsable_cargo', sa.String(length=100), nullable=True),
    sa.Column('responsable_email', sa.String(length=120), nullable=False),
    sa.Column('responsable_telefono', sa.String(length=30), nullable=False),
    sa.Column('prestadores_solicitados', sa.Text(), nullable=True),
    sa.Column('origen_institucion', sa.String(length=20), nullable=False),
    sa.Column('nivel_solicitud', sa.String(length=20), nullable=False),
    sa.Column('fecha_solicitada', sa.Date(), nullable=False),
    sa.Column('horario_preferido', sa.String(length=50), nullable=True),
    sa.Column('cantidad_alumnos', sa.Integer(), nullable=False),
    sa.Column('cantidad_docentes', sa.Integer(), nullable=True),
    sa.Column('edad_promedio', sa.String(length=50), nullable=True),
    sa.Column('nivel_educativo', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('necesidades_especiales', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_respuesta', sa.DateTime(), nullable=True),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.Column('ip_origen', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('es_super_admin', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('usuario_prestador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('prestador_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prestador_id'], ['prestador.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('visita_prestador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('prestador_id', sa.Integer(), nullable=False),
    sa.Column('fecha_confirmada', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('grupo', sa.Integer(), nullable=True),
    sa.Column('duracion_estimada', sa.Integer(), nullable=True),
    sa.Column('guia_asignado', sa.String(length=100), nullable=True),
    sa.Column('observaciones_prestador', sa.Text(), nullable=True),
    sa.Column('sala_o_area', sa.String(length=100), nullable=True),
    sa.Column('estado_visita', sa.String(length=20), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.Column('asignado_por_admin_id', sa.Integer(), nullable=True),
    sa.Column('fecha_realizacion', sa.DateTime(), nullable=True),
    sa.Column('visitantes_reales', sa.Integer(), nullable=True),
    sa.Column('calificacion', sa.Integer(), nullable=True),
    sa.Column('comentarios_finales', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asignado_por_admin_id'], ['usuario_admin.id'], ),
    sa.ForeignKeyConstraint(['prestador_id'], ['prestador.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud_visita.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visita_prestador')
    op.drop_table('usuario_prestador')
    op.drop_table('usuario_admin')
    op.drop_table('solicitud_visita')
    op.drop_table('prestador')
    # ### end Alembic commands ###
